# Generated by Django 2.1.3 on 2018-11-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task', models.CharField(max_length=255)),
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_org_id', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('deadline', models.DateField()),
                ('created', models.DateField()),
            ],
        ),
    ]
