# Generated by Django 2.1.4 on 2019-01-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otdb', '0002_auto_20190102_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task_name',
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='otdb.Status'),
        ),
    ]
