# Generated by Django 2.1.4 on 2019-01-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otdb', '0003_auto_20190102_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_tags',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='otdb.Tag'),
        ),
    ]
