# Generated by Django 2.1.4 on 2019-01-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otdb', '0005_auto_20190106_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_project_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='otdb.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='otdb.Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_tags',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='otdb.Tag'),
        ),
    ]
